### PR TITLE
fix(apiVersion): cronjob

### PR DESCRIPTION
**Pull request by Jose-Matsuda**
Thought I did the whole
https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/daaas-system/workflows-cronjob/cron.yaml#L29

but alas I still had 

https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/daaas-system/notebook-scanning/notebook-scanning.yaml#L38

### CODE REVIEW

**Comment by cboin1996** [comment]
@Jose-Matsuda shouldn't it be batch/v1 as per here: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ ?

**Comment by cboin1996** [comment]
Looks good to me. Saw that for v1.19 apiVersion should be /batch/v1beta1: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#cronjob-v1beta1-batch

**Comment by rohank07** [comment]
> @Jose-Matsuda shouldn't it be batch/v1 as per here: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ ?

I think our cluster are running K8s v1.19. I've heard from Brendan that CNS want to upgrade to 1.21 ASAP.

**Comment by Jose-Matsuda** [comment]
> @Jose-Matsuda shouldn't it be batch/v1 as per here: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ ?

In 1.19 of the docs it does use the /batch/v1beta1, which is the version I believe we are currently on. Should also be noted that I do see the error out in argocd 

image

Whereas the argo-workflow cronjob is just a-ok
image

**Review by cboin1996 — APPROVED** [review]
LGTM. Version 1.19 specifies batch/v1beta1 as the apiVersion.

**Pull request merged**
